export interface FaqItem {
  q: string;
  a: string;
}

export interface BlogPost {
  slug: string;
  title: string;
  description: string;
  date: string;
  readTime: number;
  tags: string[];
  image: string;
  faq: FaqItem[];
}

export const posts: BlogPost[] = [
  {
    slug: 'asenumerable-vs-tolist-vs-asqueryable',
    title: 'AsEnumerable vs ToList vs AsQueryable in EF Core: Where SQL Stops and C# Starts',
    description: 'All three decide where your query stops being SQL and starts being C#. AsEnumerable streams and stays deferred; ToList buffers and runs immediately; AsQueryable on a List buys you nothing. Learn where to put the hand-off, why the streaming promise needs AsNoTracking, and the AsQueryable trap that only breaks in your tests.',
    date: '2026-07-14',
    readTime: 8,
    tags: ['.NET', 'EF Core', 'C#', 'LINQ', 'Testing'],
    image: '/images/handoff.png',
    faq: [
      { q: 'What is the difference between AsEnumerable and ToList?', a: 'Both switch the query to client evaluation. AsEnumerable stays deferred and streams the results; ToList executes immediately and buffers everything into a list, which takes additional memory. Prefer AsEnumerable when you pass through the rows once, and ToList when you enumerate several times, since the list means only one trip to the database.' },
      { q: 'Does AsEnumerable really use constant memory?', a: 'Only on a no-tracking query. On a tracking query - the default - the DbContext keeps a reference to every entity it materialises, no matter which operators you use afterwards, so the rows are not really released until the context is disposed. If you are streaming rows in order to discard most of them, combine AsEnumerable with AsNoTracking.' },
      { q: 'Does calling AsQueryable() on a List give me SQL translation?', a: 'No. On an in-memory collection it produces an EnumerableQuery, a queryable-shaped wrapper whose provider still executes everything in memory. There is no database behind it, so no SQL is generated and none can be. It satisfies a method signature; it does not make anything faster.' },
      { q: 'Why does ToListAsync throw when I mock a DbSet with AsQueryable?', a: 'Because an EnumerableQuery\'s provider is not an IAsyncQueryProvider and the source is not an IAsyncEnumerable, so EF Core\'s async operators - ToListAsync, FirstOrDefaultAsync, CountAsync - have nothing to work with and throw at runtime. It is why libraries like MockQueryable exist, and why the EF Core testing docs call mocking DbSet for querying "complex and difficult" and discourage it, pointing to SQLite in-memory mode or your real database system instead.' },
      { q: 'Do I need AsEnumerable to call a C# method in my query?', a: 'Not if the method is only in the final Select. EF Core supports partial client evaluation in the top-level projection, so it fetches the columns it needs and runs your method on the results. You only need a hand-off when the untranslatable code sits in a Where, an OrderBy, or a join - and there EF Core throws rather than silently pulling the table into memory.' },
      { q: 'Can AsQueryable() rescue a query that was typed as IEnumerable?', a: 'Yes, technically. If the object is still a real EF Core query and was only typed as IEnumerable, AsQueryable returns the original IQueryable, provider intact, so subsequent operators are translated again. It is a good demonstration that the static type was the only problem - but it is a patch over a broken signature. Fix the type instead.' },
    ],
  },
  {
    slug: 'ienumerable-vs-iqueryable',
    title: 'IEnumerable vs IQueryable in EF Core: Why the Wrong Type Loads Your Whole Table',
    description: 'The difference is not the interface - it is the type of the lambda. Queryable.Where takes an expression tree EF Core can translate to SQL; Enumerable.Where takes a delegate it cannot read. Learn why switching to IEnumerable before you filter makes EF Core load the whole table, why its translation guard cannot save you there, and the overload trap that does it behind your back.',
    date: '2026-07-13',
    readTime: 8,
    tags: ['.NET', 'EF Core', 'C#', 'LINQ', 'Performance'],
    image: '/images/iqueryable.png',
    faq: [
      { q: 'What is the real difference between IEnumerable and IQueryable?', a: 'The type of the lambda the LINQ operator accepts. Queryable.Where takes an Expression<Func<T, bool>> - an expression tree EF Core can inspect and translate into SQL. Enumerable.Where takes a Func<T, bool> - a compiled delegate that can only be invoked, never inspected. IQueryable also inherits from IEnumerable, which is why the mistake compiles silently.' },
      { q: 'Why does typing a query as IEnumerable cause a full table scan?', a: 'It does so when the type changes before you filter - which is the usual case, because a repository returns IEnumerable and the caller filters afterwards. The compiler then binds every operator to the in-memory versions, EF Core is never given the predicate, and it cannot put it in the WHERE clause. It sends a SELECT with no WHERE and reads and transfers the entire table - the point being that every row crosses the wire and is materialised into an entity, not which operator the execution plan happens to pick - and your delegate then filters them in your process. Worse, a tracking query (the default) snapshots every one of those entities in the change tracker, including the ones you are about to discard. Note the ordering matters: anything you composed while the query was still IQueryable is still translated, so an IQueryable filtered first and only then assigned to an IEnumerable variable does produce a proper WHERE clause.' },
      { q: 'Doesn\'t EF Core throw when it cannot translate something?', a: 'Yes, but only inside IQueryable. Since EF Core 3.0, an expression it cannot translate anywhere other than the top-level projection causes a runtime exception rather than a silent client-side fallback. That guard fires when EF tries to translate and fails. If you typed the variable as IEnumerable, EF is never asked to translate anything, so there is nothing to fail and nothing to throw - you just get a table scan.' },
      { q: 'Should my repository return IQueryable?', a: 'It is a genuine trade-off. Returning IQueryable keeps queries composable and translatable, but it leaks EF Core into the caller and lets anyone write a query you never reviewed. Returning IEnumerable hides EF Core but silently kills translation. A middle path is to accept the filter as a parameter and return a projected DTO, so composition happens inside the repository where you control it.' },
    ],
  },
  {
    slug: 'ef-core-transactions',
    title: 'Transactions in EF Core: What SaveChanges Already Does, and When to Take Over',
    description: 'EF Core wraps every SaveChanges call in a transaction, so a single save is already atomic. You need BeginTransaction only when the all-or-nothing unit spans more than one save. Learn the automatic savepoints, the MARS trap that silently disables them, why explicit transactions throw once you enable retries, and how to share one transaction across contexts.',
    date: '2026-07-13',
    readTime: 8,
    tags: ['.NET', 'EF Core', 'C#', 'Database', 'Backend'],
    image: '/images/eftransactions.png',
    faq: [
      { q: 'Does SaveChanges run inside a transaction by default?', a: 'Yes. If the provider supports transactions, all changes in a single SaveChanges call are applied in one transaction. If any change fails, the whole call is rolled back and the database is left unmodified. You do not need BeginTransaction to make a single save atomic.' },
      { q: 'When do I actually need BeginTransaction?', a: 'When the all-or-nothing unit is bigger than one save: several SaveChanges calls, a SaveChanges combined with ExecuteUpdate or ExecuteDelete (which do not start a transaction of their own), raw SQL mixed with EF Core, or two DbContext instances that must commit together.' },
      { q: 'Why do I get "does not support user-initiated transactions"?', a: 'Because you enabled a retrying execution strategy (EnableRetryOnFailure) and then opened a transaction yourself. EF cannot know how to replay your transaction after a transient failure, so it throws. The fix is to get an execution strategy from DbContext.Database.CreateExecutionStrategy() and run the whole transaction inside strategy.ExecuteAsync, so it can be retried as one unit.' },
      { q: 'Does EF Core create savepoints automatically?', a: 'Yes. When SaveChanges is called while a transaction is already open on the context, EF creates a savepoint first. If the save fails, it rolls back to that savepoint, so the transaction is left as if the save never happened and you can correct the problem and retry.' },
      { q: 'Why would savepoints silently stop working?', a: 'Because of MARS. The docs state savepoints are incompatible with SQL Server\'s Multiple Active Result Sets, and EF will not create them when MARS is enabled on the connection - even if MARS is not actively used. If SaveChanges then fails inside a transaction, the transaction may be left in an unknown state. Check your connection string for MultipleActiveResultSets=True.' },
      { q: 'Can I use TransactionScope with async code?', a: 'Yes, but you must pass TransactionScopeAsyncFlowOption.Enabled to the constructor, otherwise the ambient transaction does not flow across await calls. Also note that TransactionScope has no async commit or rollback - disposing it blocks the thread - and distributed transactions only work on .NET 7 or later, on Windows.' },
    ],
  },
  {
    slug: 'aspnet-core-background-jobs-race-conditions',
    title: 'The Conditional UPDATE: Safe Background Jobs Across Many ASP.NET Core Instances',
    description: 'EF Core\'s ExecuteUpdateAsync returns the number of rows it changed. Put your precondition in the WHERE clause and that number becomes a verdict - zero means someone beat you to it. Microsoft documents this as concurrency control you implement yourself. Here is the technique, the check-then-act race it kills, and how it lets many instances share one job table safely.',
    date: '2026-07-13',
    readTime: 8,
    tags: ['.NET', 'ASP.NET Core', 'EF Core', 'Concurrency', 'Backend'],
    image: '/images/jobclaiming.png',
    faq: [
      { q: 'What does ExecuteUpdateAsync actually return, and why does it matter?', a: 'It returns the number of rows the UPDATE affected. EF Core\'s docs present this as a way of implementing concurrency control yourself: put a precondition in the WHERE clause, and if the call reports zero rows, the precondition was no longer true when the write reached the database. That row count is the whole safety mechanism.' },
      { q: 'Why is reading a row and then updating it unsafe?', a: 'Because the check and the act are two separate trips to the database, and anything can happen in the gap. Two callers can both pass the check before either one writes, and both writes then succeed because each is a legal update. Nothing throws, so the failure is silent. A conditional UPDATE removes the gap by making the check part of the write.' },
      { q: 'Do background services run on every instance of my app?', a: 'Yes. A BackgroundService or IHostedService runs inside the app host, and every instance is its own host. Four instances means four copies of the worker running at the same time. If the worker polls for jobs, they all compete for the same rows.' },
      { q: 'Why do job leases need an expiry?', a: 'Because workers crash. If a worker dies while holding a job and the lease never expires, that job stays locked forever and nothing picks it up again. An expiry makes abandoned jobs claimable once more. The trade-off is that a worker whose lease expired may still be running, which is why completion also has to verify ownership.' },
      { q: 'Can I guarantee a job runs exactly once?', a: 'No, and designing as though you can is the mistake. A worker can always crash after doing the work but before recording that it did, and the retry that follows is correct behaviour. Design for at-least-once execution and make the side effects idempotent - usually with a unique key that makes a duplicate insert fail - so that a retry cannot corrupt anything.' },
      { q: 'Does ExecuteUpdateAsync run inside a transaction?', a: 'Not on its own. The EF Core docs state that ExecuteUpdate and ExecuteDelete do not implicitly start a transaction, so each call runs in its own. The single UPDATE is still atomic by itself, which is all the claim requires. If a claim must succeed or fail together with another write, start a transaction explicitly.' },
    ],
  },
  {
    slug: 'aspnet-core-stateless-web-api',
    title: 'How to Make Your ASP.NET Core Web API Stateless: Redis, HybridCache and Shared Storage',
    description: 'Part two of the horizontal scale series. Move the state that must be shared out of the web process: a distributed cache instead of IMemoryCache, HybridCache with stampede protection, a Redis-backed output cache, and shared object storage - plus what it costs you and what you can safely leave local.',
    date: '2026-07-12',
    readTime: 7,
    tags: ['.NET', 'ASP.NET Core', 'Web API', 'Redis', 'Caching'],
    image: '/images/distributedstate.png',
    faq: [
      { q: 'Does AddDistributedMemoryCache actually distribute anything?', a: 'No. The docs are explicit: the distributed memory cache "isn\'t an actual distributed cache. The app instance stores the cached items on the server where the app is running." It implements IDistributedCache so you can swap in a real provider later, and it is useful for development and testing, but in a scaled-out deployment it gives you a per-instance cache.' },
      { q: 'Should I use HybridCache or IDistributedCache directly?', a: 'Prefer HybridCache for new code. It gives you a two-level cache (in-process L1 plus your distributed L2), handles serialization, and adds stampede protection. It uses whatever IDistributedCache you registered as its secondary store, so you still choose Redis, SQL Server, or Postgres underneath.' },
      { q: 'What is a cache stampede, and how does HybridCache prevent it?', a: 'A stampede happens when a popular cache entry expires and many concurrent requests all miss at once, so they all hit the database to rebuild the same value. HybridCache ensures that only one concurrent caller for a given key calls the factory method, and all other callers wait for that result. You get this even without a distributed cache configured.' },
      { q: 'If I invalidate a cache entry, do all instances see it immediately?', a: 'Not entirely. Removing by key or tag invalidates the entry on the current server and in the distributed store, but the docs note that the in-memory cache on other servers is not affected. Their L1 copies survive until they expire. If a value must go stale everywhere at once, use a short LocalCacheExpiration or avoid caching it locally.' },
      { q: 'Do I need Redis just to run more than one instance?', a: 'Not necessarily. It depends on which state must actually be shared. If your API is token-based and its caches are read-through over a database, several instances can run happily with only local caches. You need a shared store when correctness depends on instances agreeing - global rate limits, shared output cache, coordinated background work.' },
      { q: 'Is there a size limit on what I can cache?', a: 'Yes. HybridCache has a MaximumPayloadBytes option that defaults to 1 MB, and a MaximumKeyLength that defaults to 1024 characters. Attempts to store values above the limit are logged and the value is not cached - so a silently empty cache is often an oversized payload.' },
    ],
  },
  {
    slug: 'aspnet-core-stateful-assumptions',
    title: 'Why Your ASP.NET Core Web API Breaks When You Scale It Horizontally',
    description: 'A Web API is supposed to be stateless, but several ASP.NET Core defaults are not. Run two instances and the built-in rate limiter, output cache, and in-memory cache each keep their own copy per process - so a "100 per minute" limit becomes 100 per instance. Learn which defaults break and how to move that state to a distributed store.',
    date: '2026-07-10',
    readTime: 6,
    tags: ['.NET', 'ASP.NET Core', 'Web API', 'Scalability', 'Backend'],
    image: '/images/statelessapps.png',
    faq: [
      { q: 'Does the built-in ASP.NET Core rate limiter work across multiple instances?', a: 'Each instance enforces the limit in its own process memory, with no distributed store behind it. That is fine when the limit protects each instance own capacity - the total throughput simply scales with the number of instances. It is a problem when the limit is meant to be global, like a per-caller quota or protection for a shared resource, because one caller requests are spread across instances and the effective limit multiplies. For a global limit, use a distributed rate limiter backed by Redis, or enforce it at the gateway or ingress layer.' },
      { q: 'Is output caching shared across servers?', a: 'Not by default. The default output cache store is in-process, so each server has a separate cache that is lost when the process restarts. To share cached responses across instances, use the Redis-backed store via AddStackExchangeRedisOutputCache.' },
      { q: 'Is IMemoryCache shared between instances?', a: 'No. IMemoryCache lives inside the web process, so each instance keeps its own cache. For read-through caching over a database this is usually acceptable, since the database remains the source of truth. For shared cache state, use a distributed cache or HybridCache with a distributed backing store.' },
      { q: 'Do I need sticky sessions for a Web API?', a: 'Usually not. A token-based, stateless API does not need stickiness. You only need it if you keep per-user state in process memory, and even then the Microsoft docs recommend externalizing that state to a distributed store instead, because sticky sessions hurt scalability and complicate deployments.' },
      { q: 'Are singletons and background services per instance?', a: 'Yes. A singleton is one object per process, not per deployment, so two instances have two separate singletons. A BackgroundService starts inside every app host, so every instance runs its own copy of the worker. Both are safe on one process and need care once you scale out.' },
      { q: 'My API uses cookie auth - why do users get logged out after scaling?', a: 'Because each instance generates its own Data Protection key ring by default, and cookies encrypted by one instance cannot be decrypted by another. If your API issues auth cookies or antiforgery tokens, persist a shared key ring (file share, Blob, Redis, or database) and set the same application name on every instance.' },
    ],
  },
  {
    slug: 'dotnet-per-operation-timeouts',
    title: 'Per-Operation Timeouts in .NET: Why HttpClient.Timeout Is Not Enough',
    description: 'HttpClient.Timeout is infrastructure-level - it applies the same budget to every call. Learn how to use CancellationTokenSource and CreateLinkedTokenSource to set per-operation timeouts that compose with the caller token and tell you exactly who cancelled.',
    date: '2026-07-03',
    readTime: 7,
    tags: ['.NET', 'C#', 'Backend', 'Resilience'],
    image: '/images/timeoutboundary.png',
    faq: [
      { q: 'Why set HttpClient.Timeout to Timeout.InfiniteTimeSpan?', a: 'Because the timeout belongs at the operation level, not the infrastructure level. Setting HttpClient.Timeout applies the same budget to every call. Moving the timeout to a per-call CancellationTokenSource lets each operation define its own budget based on what the business logic requires.' },
      { q: 'What does CreateLinkedTokenSource actually do?', a: 'It creates a new CancellationTokenSource that is cancelled when any of the source tokens cancel - a logical OR. The resulting token stops the operation at whichever boundary fires first: the caller disconnecting, the time budget expiring, or any other token in the chain.' },
      { q: 'How do I know if the timeout or the caller cancelled?', a: 'Check timeoutCts.IsCancellationRequested and the caller token separately after catching OperationCanceledException. If timeoutCts fired but the caller token did not, it was your budget. If the caller token fired, the client closed the connection and no response is needed.' },
      { q: 'What happens if I don\'t dispose the linked CancellationTokenSource?', a: 'CreateLinkedTokenSource registers callbacks on the parent tokens. Without disposal those callbacks are never removed, keeping the linked CTS alive in memory. On a high-throughput service this becomes a memory leak on every request.' },
      { q: 'Should I use raw CancellationTokenSource or Polly?', a: 'For simple timeout-only scenarios, raw CancellationTokenSource is fine. When you need retry, circuit breaking, and timeout composing together, Polly is the better choice. Understanding the raw mechanism helps you configure and debug the abstraction correctly.' },
      { q: 'Where does the caller\'s CancellationToken come from in ASP.NET Core?', a: 'It is HttpContext.RequestAborted, injected automatically when you declare a CancellationToken parameter in a minimal API handler or controller action. It fires when the client closes the connection or the request times out at the server level.' },
    ],
  },
  {
    slug: 'python-multiple-inheritance',
    title: 'Python Inheritance Explained: Simple, Chain, Hierarchical and Multiple',
    description: 'Python supports four types of inheritance. Learn how simple, chain, hierarchical, and multiple inheritance work with practical examples, how the MRO resolves method conflicts, and when to prefer composition over inheritance.',
    date: '2026-07-02',
    readTime: 7,
    tags: ['Python', 'OOP', 'Backend'],
    image: '/images/pythoninheritance.png',
    faq: [
      { q: 'What are the four types of inheritance in Python?', a: 'Simple (one parent, one subclass), chain or multilevel (a subclass becomes a parent itself), hierarchical (multiple subclasses from the same parent), and multiple (one class inherits from more than one parent).' },
      { q: 'What is the MRO in Python?', a: 'The Method Resolution Order is the search path Python follows when looking up a method in a class hierarchy. It is computed automatically using the C3 linearization algorithm. You can inspect it with ClassName.__mro__.' },
      { q: 'Does the order of parent classes in multiple inheritance matter?', a: 'Yes. The order in the class definition determines the MRO. Python searches parent classes left to right. If two parents define the same method, the one listed first wins.' },
      { q: 'Why should I use super() instead of calling the parent class directly?', a: 'In multiple inheritance, super() calls the next class in the MRO, not necessarily the direct parent. This makes cooperative inheritance work - all classes in the chain get called in the right order. Calling a parent directly by name can silently skip parts of the hierarchy.' },
      { q: 'When should I use multiple inheritance?', a: 'The safest use case is the Mixin pattern - small classes that add one specific capability without defining a primary identity. Avoid it when parent classes share state, have conflicting methods, or when the combination has no clear conceptual meaning.' },
      { q: 'What is the difference between chain inheritance and hierarchical inheritance?', a: 'Chain (multilevel) inheritance goes vertically - A inherits from B, and B inherits from C. Hierarchical inheritance goes horizontally - multiple classes all inherit from the same single parent, branching in different directions.' },
    ],
  },
  {
    slug: 'ef-core-design-patterns',
    title: 'EF Core Under the Hood: 11 Design Patterns You Use Every Day',
    description: 'EF Core implements Unit of Work, Repository, Identity Map, Strategy, Builder, Factory, Object Pool, Interceptor, Template Method, Query Object, and Value Object. Understanding these patterns explains most of EF Core\'s behaviour - and most of its surprises.',
    date: '2026-06-18',
    readTime: 10,
    tags: ['.NET', 'EF Core', 'Architecture', 'Design Patterns', 'Backend'],
    image: '/images/efcorepatterns.png',
    faq: [
      { q: 'Is DbContext a Unit of Work or a Repository?', a: 'Both. DbContext is the Unit of Work - it tracks changes and commits them in one transaction via SaveChanges(). DbSet<T> is the Repository - it provides the collection-like interface for querying and persisting a specific entity type.' },
      { q: 'Should I add a Repository layer on top of EF Core?', a: 'For most applications, no. DbSet<T> is already a repository, and wrapping it adds boilerplate without much benefit. A custom Repository layer makes sense when you need to fully hide EF Core from your domain or enforce a strict set of allowed queries.' },
      { q: 'What is the difference between AddDbContext and AddDbContextPool?', a: 'AddDbContext creates a new DbContext instance per scope. AddDbContextPool maintains a pool of pre-created instances and resets them between uses, reducing allocation pressure. Use it when your context has no custom constructor state.' },
      { q: 'When should I use IDbContextFactory instead of injecting DbContext directly?', a: 'Use IDbContextFactory when the standard scoped lifetime does not fit - Blazor Server components, background services, or any scenario where you need multiple short-lived contexts within the same scope.' },
      { q: 'What is the difference between OwnsOne and HasOne in EF Core?', a: 'OwnsOne maps a Value Object - the owned type has no identity of its own and its columns live in the owner\'s table. HasOne maps a relationship between two independent entities that each have their own primary key and table.' },
    ],
  },
  {
    slug: 'impedance-mismatch-explained',
    title: 'Impedance Mismatch in Software: What It Is and Why It Matters',
    description: 'Impedance mismatch describes the friction between two systems built on fundamentally different models. Learn what it means, why the object-relational mismatch is the classic example, and where EF Core abstractions leak.',
    date: '2026-06-18',
    readTime: 7,
    tags: ['.NET', 'EF Core', 'SQLAlchemy', 'Architecture', 'Backend'],
    image: '/images/impedance_mismatch.png',
    faq: [
      { q: 'Where does the term "impedance mismatch" come from?', a: 'It comes from electrical engineering, where impedance mismatch between circuit components causes power loss and signal reflection. The software community borrowed the metaphor - two systems with incompatible shapes need a bridging component, at the cost of some loss.' },
      { q: 'Does using an ORM solve the object-relational impedance mismatch?', a: 'It reduces the manual work but does not eliminate the mismatch. An ORM is the translation layer - and translation layers always have edge cases, performance surprises, and leaky abstractions. You trade writing SQL by hand for learning the ORM\'s behaviour in detail.' },
      { q: 'What is the N+1 query problem?', a: 'It happens when you load a list of N entities and then trigger one additional query for each entity to load a related object. One query becomes N+1 queries. In EF Core the fix is to use Include() to eager-load the related data in a single query.' },
      { q: 'What is the difference between IQueryable and IEnumerable in EF Core?', a: 'IQueryable builds an expression tree that EF Core translates to SQL - filtering and sorting happen in the database. IEnumerable triggers execution immediately and any subsequent operations happen in memory. Using IEnumerable where IQueryable is expected can load entire tables into memory.' },
      { q: 'Should I always use an ORM?', a: 'Not always. ORMs are well suited for CRUD-heavy applications with straightforward data models. For read-heavy reporting, complex aggregations, or bulk data operations, raw SQL or a micro-ORM like Dapper often gives you better control and performance.' },
      { q: 'Is impedance mismatch only relevant to databases?', a: 'No. The concept appears anywhere two systems with fundamentally different models need to communicate - sync vs async boundaries, REST APIs vs domain models, microservices with overlapping entities, and serialisation formats. Wherever you see a translation layer, there is probably a mismatch underneath it.' },
    ],
  },
  {
    slug: 'ca2012-valuetask-correctly',
    title: 'CA2012: How to Use ValueTask Correctly in .NET',
    description: 'CA2012 catches ValueTask misuse — double awaits, stored instances, and discarded results. Learn the one-shot consumption contract, every violation pattern with code examples, and when AsTask() is the right escape hatch.',
    date: '2026-06-05',
    readTime: 7,
    tags: ['.NET', 'C#', 'Async', 'Backend'],
    image: '/images/valuetask.png',
    faq: [
      { q: 'Is CA2012 enabled by default?', a: 'From .NET 10 it is enabled as a suggestion. In earlier SDK versions it may not be active. You can enable it explicitly in .editorconfig by setting dotnet_diagnostic.CA2012.severity to warning or error.' },
      { q: 'Why can I await a Task multiple times but not a ValueTask?', a: 'Task is a class (reference type) and its completed state and result are stored on the heap indefinitely. ValueTask is a struct that may wrap a pooled IValueTaskSource — after the first await, the pool can reclaim and reuse that source object. A second await could read stale recycled data.' },
      { q: 'When should I use AsTask() instead of just calling the method again?', a: 'Use AsTask() when calling the method a second time would repeat work you do not want repeated — for example, if the method performs I/O or modifies state. If the operation is idempotent, calling it twice is cleaner and avoids the Task allocation.' },
      { q: 'Does CA2012 catch misuse of ValueTask (non-generic) too?', a: 'Yes. The rule applies to both ValueTask and ValueTask<T>. Both have the same one-shot consumption contract.' },
      { q: 'Can I suppress CA2012 at the project level?', a: 'Yes, but you should not do this globally. CA2012 catches real bugs. If you find yourself suppressing it broadly, the underlying code should be fixed instead.' },
      { q: 'Should I always prefer ValueTask over Task?', a: 'No. Task is the right default. ValueTask is an optimisation for hot paths where the operation frequently completes synchronously and allocation pressure is measurable. Use Task unless profiling shows a real benefit from switching.' },
    ],
  },
  {
    slug: 'csharp-records-vs-classes',
    title: 'C# Records vs Classes: When to Use Each and Why',
    description: 'Records and classes look similar in C# but behave very differently. Learn how value equality, with expressions, and immutability make records the right choice for data models - and when to stick with classes.',
    date: '2026-06-04',
    readTime: 6,
    tags: ['C#', '.NET', 'Backend'],
    image: '/images/csharp-records.png',
    faq: [
      { q: 'When were records introduced in C#?', a: 'Record classes were introduced in C# 9 (released with .NET 5 in November 2020). Record structs and readonly record structs were added in C# 10 (released with .NET 6 in November 2021).' },
      { q: 'Are records immutable in C#?', a: 'Positional record class properties are init-only by default, meaning they cannot be changed after the object is constructed. However, you can declare a record with mutable set properties if needed. Record structs are mutable by default - use readonly record struct for immutability.' },
      { q: 'What does the with expression do?', a: 'A with expression creates a new record instance that is a shallow copy of an existing one, with one or more properties changed. The original is never modified.' },
      { q: 'Can I use a record as a dictionary key?', a: 'Yes. Because records implement value equality and override GetHashCode, two records with the same data produce the same hash code and are treated as equal keys in a dictionary.' },
      { q: 'What is the difference between record and record class?', a: 'They are identical. The record keyword on its own defines a reference type, which is the same as writing record class explicitly. The explicit record class form was introduced in C# 10 to make the distinction from record struct clearer.' },
      { q: 'Can a regular class inherit from a record?', a: 'No. A regular class cannot inherit from a record, and a record cannot inherit from a regular class. Records can only inherit from other records.' },
    ],
  },
  {
    slug: 'dotnet-task-async-await',
    title: 'Understanding Task in .NET: The Unit of Asynchronous Work',
    description: 'A deep dive into what Task really is in .NET, how async/await works under the hood, and the pitfalls that cause deadlocks, lost exceptions, and performance problems in production.',
    date: '2026-06-04',
    readTime: 12,
    tags: ['.NET', 'C#', 'Async', 'Backend'],
    image: '/images/task.png',
    faq: [
      { q: 'What is the difference between Task and Thread in .NET?', a: 'A Thread is an OS-level execution unit. A Task is a higher-level abstraction representing an operation that may or may not use a thread. Many tasks (especially I/O-bound ones) complete without ever blocking a thread.' },
      { q: 'When should I use Task.Run?', a: 'Use Task.Run only for CPU-bound work that you want to offload from the current thread. Do not use it to wrap I/O-bound async calls - that wastes a thread-pool thread waiting for I/O that did not need one.' },
      { q: 'What causes a deadlock in async .NET code?', a: 'Calling .Result or .Wait() on a Task in an environment with a SynchronizationContext (WPF, WinForms, classic ASP.NET). The calling thread blocks waiting for the Task, but the Task\'s continuation needs that same thread to run.' },
      { q: 'What is the difference between await and .Result?', a: 'await suspends the method without blocking a thread and unwraps the AggregateException, rethrowing the actual exception type. .Result blocks the calling thread and throws the full AggregateException wrapper.' },
      { q: 'What is ConfigureAwait(false) and when should I use it?', a: 'ConfigureAwait(false) tells the runtime not to capture the current SynchronizationContext when resuming after an await. Use it in library code to avoid unnecessary context switching and reduce deadlock risk for callers.' },
      { q: 'What is ValueTask and when should I use it?', a: 'ValueTask is a struct alternative to Task that avoids a heap allocation when the result is already available synchronously. Use it on hot paths where the operation frequently completes synchronously. Always await it exactly once.' },
    ],
  },
  {
    slug: 'sql-joins-inner-left-right',
    title: 'SQL JOINs Explained: INNER, LEFT, RIGHT, FULL OUTER and SELF JOIN with Examples',
    description: 'A clear explanation of SQL INNER JOIN, LEFT JOIN, RIGHT JOIN, FULL OUTER JOIN and SELF JOIN with practical examples. Learn what each join returns and when to use it.',
    date: '2026-06-03',
    readTime: 5,
    tags: ['SQL', 'Database', 'Backend'],
    image: '/images/sql-joins.png',
    faq: [
      { q: 'What is the difference between INNER JOIN and LEFT JOIN?', a: 'INNER JOIN only returns rows with a match in both tables. LEFT JOIN returns all rows from the left table, with NULLs where no match exists in the right table.' },
      { q: 'Is LEFT JOIN the same as LEFT OUTER JOIN?', a: 'Yes. LEFT JOIN and LEFT OUTER JOIN are identical. The OUTER keyword is optional.' },
      { q: 'Which JOIN is the fastest?', a: 'INNER JOIN is typically the fastest because it processes fewer rows. However, performance depends mostly on indexes, not the JOIN type.' },
      { q: 'Can I use multiple JOINs in one query?', a: 'Yes. You can chain as many JOINs as needed in a single query, each with its own ON condition.' },
      { q: 'What is a FULL OUTER JOIN?', a: 'FULL OUTER JOIN returns all rows from both tables, matching them where it can and filling in NULL where it cannot. You get matched rows (from both sides), unmatched left rows (right columns = NULL), and unmatched right rows (left columns = NULL). Note: MySQL does not support FULL OUTER JOIN natively.' },
      { q: 'What is a SELF JOIN?', a: 'A SELF JOIN joins a table with itself using two different aliases. It is useful for querying hierarchical data, such as employees and their managers stored in the same table.' },
    ],
  },
  {
    slug: 'az-204-retirement-ai-200',
    title: 'AZ-204 Is Retiring: What Azure Developers Need to Know About AI-200',
    description: 'Microsoft is retiring the AZ-204 Azure Developer Associate certification on July 31, 2026, replacing it with AI-200. As someone who holds AZ-204, here is everything I found out — what changes, what stays, and what you should do next.',
    date: '2026-06-02',
    readTime: 4,
    tags: ['Azure', 'Certification', 'AI-200', 'AZ-204', 'Microsoft'],
    image: '/images/azure-developer.png',
    faq: [
      { q: 'When does AZ-204 retire?', a: 'AZ-204 retires on July 31, 2026.' },
      { q: 'What replaces AZ-204?', a: 'AZ-204 is replaced by Exam AI-200: Developing AI Cloud Solutions on Azure, leading to the Microsoft Certified: Azure AI Cloud Developer Associate credential.' },
      { q: 'Will my AZ-204 certification still be valid after retirement?', a: 'Yes. Your certification remains valid and on your transcript until it naturally expires. Retirement does not invalidate certifications already earned.' },
      { q: 'Can I renew AZ-204 after July 31, 2026?', a: 'No. After the retirement date, renewal is no longer possible. If your renewal window falls after July 31, 2026, you will need to earn AI-200 instead.' },
      { q: 'Is AZ-204 still valid as a prerequisite for AZ-400 after retirement?', a: 'Yes. Microsoft has confirmed that AZ-204 will continue to satisfy the AZ-400 prerequisite as long as it is valid on your transcript.' },
      { q: 'Should I still take AZ-204 before it retires?', a: 'If you are already well into your preparation, finishing AZ-204 is still worthwhile. If you are just starting, AI-200 is the better long-term investment.' },
    ],
  },
];
